default: &default
  wunderground_key: <%= ENV['WUNDERGROUND_KEY'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  mandrill_username: <%= ENV['MANDRILL_USERNAME'] %>
  mandrill_apikey: <%= ENV['MANDRILL_APIKEY'] %>
  new_relic_license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>

development:
  <<: *default
  secret_key_base: <%= ENV['SECRET_TOKEN_DEVELOPMENT'] %>

test:
  <<: *default
  secret_key_base: <%= ENV['SECRET_TOKEN_TEST'] %>

production:
  <<: *default
  secret_key_base: <%= ENV['SECRET_TOKEN'] %>
